services:
  orders-db:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_pass
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    networks:
      - paymentflow-net

  payments-db:
    image: postgres:16-alpine
    container_name: payments-db
    environment:
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_pass
      POSTGRES_DB: payments_db
    ports:
      - "5434:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data
    networks:
      - paymentflow-net

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - orders-db
      - payment-service
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://orders_user:orders_pass@orders-db:5432/orders_db
      PAYMENT_PROVIDER_URL: http://payment-service:8000/api/payments
      ORDER_WEBHOOK_SECRET: supersecret-signing-key
      JWT_SECRET: super_jwt_secret_change_me
      JWT_ISSUER: paymentflow-auth
      ACCESS_TOKEN_EXPIRES_IN_SECONDS: 900
      REFRESH_TOKEN_SECRET: super_refresh_secret_change_me
      REFRESH_TOKEN_EXPIRES_IN_SECONDS: 604800
    ports:
      - "4000:4000"
    networks:
      - paymentflow-net

  payment-service:
    build:
      context: ../payment-service
    container_name: payment-service
    depends_on:
      - payments-db
    environment:
      PORT: 8000
      DATABASE_URL: postgresql+asyncpg://payments_user:payments_pass@payments-db:5432/payments_db
      ORDER_SERVICE_WEBHOOK: http://order-service:4000/api/webhooks/payment
      SIGNING_SECRET: supersecret-signing-key
    ports:
      - "8000:8000"
    networks:
      - paymentflow-net

networks:
  paymentflow-net:

volumes:
  orders_db_data:
  payments_db_data:
